apiVersion: v1
kind: Service
metadata:
  name: mysql-db-dep
  namespace: final
  labels:
    app: mysql
    env: prod
spec:
  type: ClusterIP
  ports:
  - name: mysql-db-dep
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    env: prod
