apiVersion: v1
kind: Service
metadata:
  name: "mysql-app-dep-lb"
  namespace: final
  labels:
    app: employees
spec:
  selector:
    app: employees
  ports:
    - protocol: TCP
      port: 81
      targetPort: 81
  type: LoadBalancer
