apiVersion: v1
kind: Service
metadata:
  name: mysql-app-dep-np
  namespace: final2
  labels:
    app: employees
spec:
  type: NodePort
  selector:
    app: employees
  ports:
  - name: ext30000
    port: 81
    targetPort: 81
    protocol: TCP
    nodePort: 30000
