apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: employees
    app.kubernetes.io/component: frontend
spec:
  containers:
  - name: employees
    image: 394986257079.dkr.ecr.us-east-1.amazonaws.com/clo835-assignment1-app:app.latest
    # image: gcr.io/google-samples/gb-frontend:v4
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
    env:
    - name: DBHOST
      value: "mysql"
    - name: DBPORT
      value: "3306"
    - name: DBUSER
      value: "root"
    - name: DATABASE
      value: "employees"
    - name: DBPWD
      value: "db_pass123"  
    ports:
    - containerPort: 8080